// Loot Goblins v0.7.1 — Mechanical QA / Rules Lock / Mechanics Lock Audit
// Mechanical baseline: classic Munchkin-style rules and the clearer English source card sheets provided by the user.
// Names, rules wording, and flavor are original Loot Goblins presentation.

const role = (id, publicName, publicText, flavorText, mechanicalSlot, copies = 1) => ({ id, deck: 'CHAMBER', type: 'ROLE', publicName, publicText, flavorText, mechanicalSlot, enforcement: 'GUIDED', copies });
const origin = (id, publicName, publicText, flavorText, mechanicalSlot, copies = 1) => ({ id, deck: 'CHAMBER', type: 'ORIGIN', publicName, publicText, flavorText, mechanicalSlot, enforcement: 'GUIDED', copies });
const foe = (id, publicName, strength, lootReward, consequence, opts = {}) => ({
  id, deck: 'CHAMBER', type: 'THREAT', publicName, strength,
  renownReward: opts.renownReward || 1, lootReward,
  publicText: opts.publicText || `Defeat this Foe to gain ${opts.renownReward || 1} Glory and draw ${lootReward} Loot.${opts.badNewsText ? ` Bad News: ${opts.badNewsText}` : ''}`,
  flavorText: opts.flavorText || 'The dungeon insists this is normal.',
  tags: opts.tags || [], specialRules: opts.specialRules || [], willNotPursue: opts.willNotPursue || [],
  consequence: consequence || { type: 'NO_EFFECT' }, enforcement: opts.enforcement || 'AUTO', copies: opts.copies || 1
});
const hex = (id, publicName, publicText, flavorText, effects, copies = 1, enforcement = 'AUTO') => ({
  id, deck: 'CHAMBER', type: 'HEX', publicName, publicText, flavorText,
  timing: ['ON_REVEAL', 'ANY_TIME'], target: 'ANY_PLAYER', effects, enforcement, copies
});
const mod = (id, publicName, strengthDelta, lootDelta, flavorText, copies = 1) => ({
  id, deck: 'CHAMBER', type: 'THREAT_MODIFIER', publicName,
  publicText: `Play during combat. Attach to a Foe. That Foe gets ${strengthDelta > 0 ? '+' : ''}${strengthDelta} strength and is worth ${lootDelta > 0 ? '+' : ''}${lootDelta} Loot.`,
  flavorText, timing: ['DURING_COMBAT'], target: 'ACTIVE_FOE', strengthDelta, lootDelta,
  discardAfterCombat: true, enforcement: 'AUTO', copies
});
const gear = (id, publicName, publicText, flavorText, stats = {}) => ({
  id, deck: 'LOOT', type: 'GEAR', publicName, publicText, flavorText,
  slot: stats.slot || 'NO_SLOT', handsUsed: stats.handsUsed || 0, combatBonus: stats.combatBonus || 0,
  escapeBonus: stats.escapeBonus || 0, scrapValue: stats.junkValue ?? 0, junkValue: stats.junkValue ?? 0,
  isHeavy: Boolean(stats.isHeavy), extraHands: stats.extraHands || 0,
  usableByCallings: stats.usableByCallings || [], notUsableByCallings: stats.notUsableByCallings || [],
  usableByOrigins: stats.usableByOrigins || [], notUsableByOrigins: stats.notUsableByOrigins || [],
  manualRestriction: Boolean(stats.manualRestriction), requiresNoKin: Boolean(stats.requiresNoKin), conditionalBonuses: stats.conditionalBonuses || [], enforcement: stats.enforcement || 'AUTO', copies: stats.copies || 1
});
const trick = (id, publicName, publicText, flavorText, effect, stats = {}) => ({
  id, deck: 'LOOT', type: 'TRICK', publicName, publicText, flavorText,
  timing: stats.timing || ['DURING_COMBAT'], target: stats.target || 'COMBAT_SIDE', effect,
  scrapValue: stats.junkValue ?? 0, junkValue: stats.junkValue ?? 0, enforcement: stats.enforcement || 'AUTO', copies: stats.copies || 1
});
const special = (id, publicName, publicText, flavorText, effect, stats = {}) => ({
  id, deck: stats.deck || 'LOOT', type: 'SPECIAL', publicName, publicText, flavorText,
  timing: stats.timing || ['OWN_TURN_OUTSIDE_COMBAT'], target: stats.target || 'SELF', effect,
  scrapValue: stats.junkValue ?? 0, junkValue: stats.junkValue ?? 0, enforcement: stats.enforcement || 'AUTO', copies: stats.copies || 1
});

const chamberCards = [
  // Callings / Classes
  role('CALLING_BRUISER', 'Bruiser', 'You win tied combats. During combat, you may discard up to three cards for +3 each.', 'A practical Calling for anyone who believes every puzzle has a door-shaped solution.', 'WARRIOR_EQUIV', 3),
  role('CALLING_HEXHAND', 'Hexhand', 'During combat, you may discard your whole hand to charm away one Foe. You get its Loot but no Glory.', 'Magic is mostly confidence, hand gestures, and cleaning up later.', 'WIZARD_EQUIV', 3),
  role('CALLING_CUTPURSE', 'Cutpurse', 'During another player’s combat, discard a card to give the player side -2. On your own turn, try to steal Gear.', 'Believes sharing is important, especially when other people start.', 'THIEF_EQUIV', 3),
  role('CALLING_GRAVEFRIEND', 'Gravefriend', 'When drawing face-up, you may discard to draw from the matching discard pile instead. Against Restless Foes, discards can power stronger turns.', 'Keeps in touch with old friends, even the very old ones.', 'CLERIC_EQUIV', 3),

  // Kin / Races
  origin('KIN_BRIGHTKIN', 'Brightkin', '+1 to Flee. When you help kill a Foe, gain 1 Glory for each Foe killed, but this cannot force the final winning Glory.', 'Graceful, helpful, and only a little pleased that everyone noticed.', 'ELF_EQUIV', 3),
  origin('KIN_DEEPBORN', 'Deepborn', 'You may carry any number of Heavy Gear. Your hand limit is 6.', 'Packs like every errand might become an expedition.', 'DWARF_EQUIV', 3),
  origin('KIN_HALFSTEP', 'Halfstep', 'Once each turn, one Gear you sell counts for double Junk Value. If you fail your first Flee roll, you may discard a card and try once more.', 'Small pockets, excellent receipts.', 'HALFLING_EQUIV', 3),

  // Role expanders and rule cards
  special('SPECIAL_MIXED_KIN', 'Mixed Kin Permit', 'Play on your turn if you have a Kin. Attach this to your Kin. You may have one extra Kin. If you have only one Kin, you get its advantages but ignore its disadvantages.', 'Every branch of the family tree brought paperwork.', { type: 'ADD_EXTRA_KIN_SLOT' }, { deck: 'CHAMBER', timing: ['OWN_TURN_OUTSIDE_COMBAT'], enforcement: 'AUTO', copies: 2 }),
  special('SPECIAL_OVERQUALIFIED', 'Overqualified', 'Play on your turn if you have a Calling. Attach this to your Calling. You may have one extra Calling. If you have only one Calling, you get its advantages but ignore its disadvantages.', 'Twice the training. Half the schedule discipline.', { type: 'ADD_EXTRA_CALLING_SLOT' }, { deck: 'CHAMBER', timing: ['OWN_TURN_OUTSIDE_COMBAT'], enforcement: 'AUTO', copies: 2 }),
  special('SPECIAL_FINE_PRINT_PERMIT', 'Fine Print Permit', 'Attach this to one Gear you own. That Gear becomes legal for you even if it normally would not be.', 'It says “approved” in a font too small to challenge.', { type: 'CHEAT_GEAR' }, { deck: 'CHAMBER', timing: ['OWN_TURN_OUTSIDE_COMBAT'], enforcement: 'GUIDED' }),
  special('SPECIAL_UNEXPECTED_COMPANY_A', 'Unexpected Company', 'Play during combat with a Foe from your hand. That Foe joins the combat. Defeat the combined Foe side or Flee from each Foe.', 'The room was already full, but apparently had standards to lower.', { type: 'ADD_FOE_FROM_HAND' }, { deck: 'CHAMBER', timing: ['DURING_COMBAT'], enforcement: 'GUIDED', copies: 3 }),
  special('SPECIAL_MATCHING_PROBLEM', 'Matching Problem', 'A second copy of the current Foe appears. It has the same modifiers and rewards.', 'One problem became two and looked proud of itself.', { type: 'ADD_MATCHING_FOE' }, { deck: 'CHAMBER', timing: ['DURING_COMBAT'], enforcement: 'AUTO' }),

  // Foe modifiers / monster enhancers
  mod('FOE_MOD_PLUS_005_LOOT_001', 'Annoyingly Prepared', 5, 1, 'It brought snacks, maps, and a backup plan with tiny labels.', 2),
  mod('FOE_MOD_PLUS_005_LOOT_002', 'Suspiciously Clever', 5, 1, 'It read one book and immediately became everyone’s problem.'),
  mod('FOE_MOD_PLUS_010_LOOT_002', 'Unreasonably Ancient', 10, 2, 'The dungeon insists it has always been this old.', 1),
  mod('FOE_MOD_PLUS_010_LOOT_003', 'Humongous', 10, 2, 'A size upgrade no one ordered and everyone noticed.'),
  mod('FOE_MOD_MINUS_005_LOOT_MINUS_001', 'Baby Version', -5, -1, 'Smaller, wobblier, and still somehow scheduled for combat.'),

  // Hexes / Curses
  hex('HEX_LOSE_LEVEL', 'Reputation Leak', 'Lose 1 Glory, to a minimum of 1.', 'The dungeon heard your story and made some edits.', [{ type: 'LOSE_RENOWN', amount: 1, minimum: 1 }], 2),
  hex('HEX_LOSE_TWO_CARDS', 'Loose Pockets', 'Discard 2 cards from your hand.', 'Everything important chose the same moment to become slippery.', [{ type: 'DISCARD_FROM_HAND', count: 2, method: 'PLAYER_CHOICE' }], 1, 'GUIDED'),
  hex('HEX_LOSE_CLASS', 'Career Crisis', 'Lose your Calling. If you have no Calling, lose 1 Glory instead.', 'The dungeon appreciates your service and has accepted your resignation.', [{ type: 'LOSE_ROLE' }], 2),
  hex('HEX_LOSE_RACE', 'Identity Audit', 'Lose your Kin. If you have no Kin, nothing happens.', 'Please provide three forms of ancestry and one small apology.', [{ type: 'LOSE_ORIGIN' }], 1),
  hex('HEX_CHANGE_CLASS', 'Career Rerouting', 'If you have a Calling, discard it and reveal Chamber cards until a new Calling appears. Keep that Calling; discard the rest.', 'A new opportunity appeared with suspicious urgency.', [{ type: 'CHANGE_ROLE' }], 1, 'GUIDED'),
  hex('HEX_CHANGE_RACE', 'Kin Shuffle', 'If you have Kin, discard it and reveal Chamber cards until a new Kin appears. Keep that Kin; discard the rest.', 'Your family tree was reorganized without a meeting.', [{ type: 'CHANGE_ORIGIN' }], 1, 'GUIDED'),
  hex('HEX_CHANGE_STYLE', 'Mirror Mix-Up', '-5 to your next combat due to distraction, then no further penalty.', 'The mirror did not ask permission before making notes.', [{ type: 'NEXT_COMBAT_DELTA', amount: -5 }], 1, 'AUTO'),
  hex('HEX_LOSE_HEADGEAR', 'Hat Problem', 'Discard the Head Gear you are wearing. If none, nothing happens.', 'Your head remains. The situation around it has changed.', [{ type: 'DISCARD_GEAR', target: 'EQUIPPED_GEAR', slot: 'HEAD', choice: 'PLAYER' }], 1, 'GUIDED'),
  hex('HEX_LOSE_FOOTGEAR', 'Floor Disagreement', 'Discard the Foot Gear you are wearing. If none, nothing happens.', 'The floor has filed a formal complaint about your footwear.', [{ type: 'DISCARD_GEAR', target: 'EQUIPPED_GEAR', slot: 'FEET', choice: 'PLAYER' }], 1, 'GUIDED'),
  hex('HEX_LOSE_ARMOR', 'Armor Incident', 'Discard the Body Gear you are wearing. If none, nothing happens.', 'The armor did its best and would like that noted.', [{ type: 'DISCARD_GEAR', target: 'EQUIPPED_GEAR', slot: 'BODY', choice: 'PLAYER' }], 1, 'GUIDED'),
  hex('HEX_LOSE_SMALL_ITEM_A', 'Lose One Small Thing', 'Choose one non-Heavy Gear to discard.', 'A tiny tragedy with excellent timing.', [{ type: 'DISCARD_GEAR', target: 'PUBLIC_GEAR', slot: 'ANY', choice: 'PLAYER' }], 2, 'GUIDED'),
  hex('HEX_LOSE_BIG_ITEM', 'Lose One Heavy Thing', 'Choose one Heavy Gear to discard. If none, nothing happens.', 'Something large has chosen independence.', [{ type: 'DISCARD_GEAR', target: 'PUBLIC_GEAR', selector: 'HEAVY', choice: 'PLAYER' }], 1, 'GUIDED'),
  hex('HEX_LOSE_BEST_ITEM', 'Lose the Favorite', 'Discard the Gear giving you the biggest combat bonus. If tied, choose one.', 'The dungeon has excellent taste and terrible boundaries.', [{ type: 'DISCARD_GEAR', target: 'PUBLIC_GEAR', selector: 'HIGHEST_COMBAT_BONUS', choice: 'PLAYER' }], 1, 'GUIDED'),
  hex('HEX_INCOME_TAX', 'Dungeon Tax Day', 'Each player discards one Gear of their choice. If a player has no Gear, they lose 1 Glory.', 'The forms are in triplicate. The rage is not.', [{ type: 'INCOME_TAX' }], 1, 'GUIDED'),
  hex('HEX_CHICKEN_ON_HEAD', 'Bird on Your Head', '-1 to all your die rolls until your Head Gear is lost or discarded.', 'It is not helpful, but it is committed.', [{ type: 'ADD_DIE_PENALTY', amount: -1 }], 1, 'AUTO'),
  hex('HEX_MALIGN_MIRROR', 'Unfriendly Mirror', 'In your next combat only, you may not count Gear bonuses except Body Gear.', 'The reflection has feedback and none of it is useful.', [{ type: 'ONLY_BODY_GEAR_NEXT_COMBAT' }], 1, 'AUTO'),
  hex('HEX_DUCK_OF_DOOM', 'Doom Duck', 'Lose 2 Glory, to a minimum of 1.', 'You knew better than to pick it up. It knew that too.', [{ type: 'LOSE_RENOWN', amount: 2, minimum: 1 }], 1),
  hex('HEX_LOCAL_RULES', 'Duck of Doom', 'Lose 2 Glory, to a minimum of 1.', 'You should know better than to pick up strange ducks in dungeons.', [{ type: 'LOSE_RENOWN', amount: 2, minimum: 1 }], 1, 'AUTO'),

  // Foes / Monsters
  foe('FOE_CRABS', 'Pinch Crabs', 1, 1, { type: 'MULTI_EFFECT', effects: [{ type: 'DISCARD_GEAR', target: 'EQUIPPED_GEAR', slot: 'BODY', choice: 'AUTO_IF_SINGLE' }, { type: 'DISCARD_GEAR', target: 'EQUIPPED_GEAR', slot: 'FEET', choice: 'AUTO_IF_SINGLE' }] }, { badNewsText: 'Discard Body Gear and Foot Gear you are wearing.', publicText: 'Cannot be Fled from. Defeat this Foe to gain 1 Glory and draw 1 Loot. Bad News: discard Body Gear and Foot Gear you are wearing.', flavorText: 'Small, sideways, and completely uninterested in negotiation.', enforcement: 'AUTO', willNotPursue: [{ type: 'NEVER' }] }),
  foe('FOE_LAME_GOBLIN', 'Limping Goblin', 1, 1, { type: 'LOSE_RENOWN', amount: 1, minimum: 1 }, { badNewsText: 'Lose 1 Glory.', publicText: '+1 to Flee. Defeat this Foe to gain 1 Glory and draw 1 Loot. Bad News: lose 1 Glory.', flavorText: 'Not fast, but deeply committed to making it weird.' }),
  foe('FOE_POTTED_PLANT', 'Potted Plant', 1, 1, { type: 'NO_EFFECT' }, { badNewsText: 'None. Flee is automatic.', publicText: 'Brightkin draw +1 Loot after defeating it. Bad News: none. Flee is automatic.', flavorText: 'Technically hostile, but only in tone.', enforcement: 'AUTO', willNotPursue: [{ type: 'NEVER' }], specialRules: [{ type: 'EXTRA_LOOT_FOR_ORIGIN', originMechanicalSlot: 'ELF_EQUIV', amount: 1 }] }),
  foe('FOE_MAUL_RAT', 'Maul Mouse', 1, 1, { type: 'LOSE_RENOWN', amount: 1, minimum: 1 }, { specialRules: [{ type: 'BONUS_AGAINST_ROLE', roleMechanicalSlot: 'CLERIC_EQUIV', amount: 3 }], badNewsText: 'Lose 1 Glory.', publicText: 'A little beast from below. +3 against Gravefriends. Defeat it for 1 Glory and 1 Loot. Bad News: lose 1 Glory.', flavorText: 'Tiny paws. Large agenda.' }),
  foe('FOE_GELATINOUS', 'Gelatinous Eight-Sider', 2, 1, { type: 'DISCARD_ALL_HEAVY_GEAR' }, { publicText: '+1 to Flee. Defeat it for 1 Glory and 1 Loot. Bad News: drop all Heavy Gear.', flavorText: 'A cube would have been too predictable.', enforcement: 'AUTO', specialRules: [{ type: 'FLEE_BONUS_AGAINST', amount: 1 }] }),
  foe('FOE_FLYING_FROGS', 'Flying Frogs', 2, 1, { type: 'LOSE_RENOWN', amount: 2, minimum: 1 }, { publicText: '-1 to Flee. Defeat this Foe for 1 Glory and 1 Loot. Bad News: lose 2 Glory.', flavorText: 'They arrive loudly and leave damply.' }),
  foe('FOE_MR_BONES', 'Dapper Bones', 2, 1, { type: 'LOSE_RENOWN', amount: 2, minimum: 1 }, { tags: ['RESTLESS'], publicText: 'Restless. If you must Flee, lose 1 Glory even if you escape. Bad News: lose 2 more Glory.', flavorText: 'Polite, skeletal, and late for something.', enforcement: 'AUTO' }),
  foe('FOE_LARGE_CHICKEN', 'Large Angry Chicken', 2, 1, { type: 'LOSE_RENOWN', amount: 1, minimum: 1 }, { publicText: 'Gain +1 extra Glory if you defeat it with fire or flame. Bad News: lose 1 Glory.', flavorText: 'Dinner has organized.', enforcement: 'AUTO' }),
  foe('FOE_PIT_BULL', 'Pit Beast', 2, 1, { type: 'LOSE_RENOWN', amount: 2, minimum: 1 }, { publicText: 'You may distract it by discarding Foot Gear, a wand, pole, or staff. Bad News: lose 2 Glory.', flavorText: 'Less a guard dog, more a doorbell with teeth.', enforcement: 'AUTO' }),
  foe('FOE_LEPRECHAUN', 'Pocket Spriggan', 4, 2, { type: 'ADJACENT_TAKE_GEAR', count: 2 }, { specialRules: [{ type: 'BONUS_AGAINST_ORIGIN', originMechanicalSlot: 'ELF_EQUIV', amount: 5 }], publicText: '+5 against Brightkin. Bad News: the table takes Gear from you.', flavorText: 'Cheerful in exactly the wrong way.', enforcement: 'AUTO' }),
  foe('FOE_HARPIES', 'Harpies', 4, 2, { type: 'LOSE_RENOWN', amount: 2, minimum: 1 }, { specialRules: [{ type: 'BONUS_AGAINST_ROLE', roleMechanicalSlot: 'WIZARD_EQUIV', amount: 5 }], publicText: 'Resists magic: +5 against Hexhands. Bad News: lose 2 Glory.', flavorText: 'Their music is real, really bad.' }),
  foe('FOE_UNDEAD_HORSE', 'Restless Horse', 4, 2, { type: 'LOSE_RENOWN', amount: 2, minimum: 1 }, { tags: ['RESTLESS'], specialRules: [{ type: 'BONUS_AGAINST_ORIGIN', originMechanicalSlot: 'DWARF_EQUIV', amount: 5 }], publicText: 'Restless. +5 against Deepborn. Bad News: lose 2 Glory.', flavorText: 'Kicks, bites, and smells like unfinished business.' }),
  foe('FOE_SNAILS', 'Snails on Speed', 4, 2, { type: 'ROLL_DISCARD_OWNED' }, { publicText: '-2 to Flee. Bad News: roll a die and lose that many Gear or hand cards, your choice.', flavorText: 'Slow reputation. Fast paperwork.', enforcement: 'AUTO' }),
  foe('FOE_SHRIEKING_GEEK', 'Shrieking Geek', 6, 2, { type: 'DISCARD_ALL_IDENTITIES' }, { specialRules: [{ type: 'BONUS_AGAINST_ROLE', roleMechanicalSlot: 'WARRIOR_EQUIV', amount: 6 }], publicText: '+6 against Bruisers. Bad News: become ordinary — discard any Calling and Kin.', flavorText: 'Knows one fact and is willing to weaponize it.', enforcement: 'AUTO' }),
  foe('FOE_PLATYCORE', 'Platycore', 6, 2, { type: 'CHOOSE_DISCARD_HAND_OR_LOSE_GLORY', amount: 2 }, { specialRules: [{ type: 'BONUS_AGAINST_ROLE', roleMechanicalSlot: 'WIZARD_EQUIV', amount: 6 }], publicText: 'Resists magic: +6 against Hexhands. Bad News: discard your hand or lose 2 Glory.', flavorText: 'A beak, wings, and several unanswered questions.', enforcement: 'AUTO' }),
  foe('FOE_LAWYERS', 'Contract Imps', 6, 2, { type: 'LAWYERS_BAD_NEWS' }, { publicText: 'Will not attack Cutpurses. Bad News: each other player draws a card from your hand.', flavorText: 'Professional courtesy, weaponized.', enforcement: 'AUTO' }),
  foe('FOE_GHOULFIENDS', 'Ghoulfriends', 8, 2, { type: 'SET_TO_LOWEST_GLORY' }, { publicText: 'No Gear bonuses help against them; fight with Glory only. Bad News: your Glory becomes equal to the lowest Glory in play.', flavorText: 'They came as a group and brought matching energy.', enforcement: 'AUTO' }),
  foe('FOE_AMAZON', 'Blade Captain', 8, 2, { type: 'LOSE_ALL_ROLES_OR_GLORY', amount: 3 }, { publicText: 'May choose not to fight certain challengers. Bad News: lose your Calling(s); if none, lose 3 Glory.', flavorText: 'A duel, a lecture, or a gift. Hard to predict.', enforcement: 'AUTO' }),
  foe('FOE_FACE_SUCKER', 'Face Sucker', 8, 2, { type: 'LOSE_HEAD_OR_GLORY' }, { specialRules: [{ type: 'BONUS_AGAINST_ORIGIN', originMechanicalSlot: 'ELF_EQUIV', amount: 6 }], publicText: '+6 against Brightkin. Bad News: lose Head Gear, or lose 1 Glory if you have none.', flavorText: 'A scarf with ambitions.' }),
  foe('FOE_GAZEBO', 'Lonely Gazebo', 8, 2, { type: 'LOSE_RENOWN', amount: 3, minimum: 1 }, { publicText: 'No one can help you. You must face it alone. Bad News: lose 3 Glory.', flavorText: 'Architectural confidence at its worst.' }),
  foe('FOE_FLOATING_NOSE', 'Hovering Nose', 10, 3, { type: 'LOSE_RENOWN', amount: 3, minimum: 1 }, { publicText: 'You may bribe it with Gear worth at least 200 Junk to leave. If you lose, you cannot Flee. Bad News: lose 3 Glory.', flavorText: 'It arrived before the rest of the monster and never apologized.', enforcement: 'AUTO' }),
  foe('FOE_NET_TROLL', 'Net Troll', 10, 3, { type: 'HIGHEST_TAKE_GEAR' }, { publicText: 'No special powers, and very mad about it. Bad News: highest-Glory players each take one Gear from you.', flavorText: 'A simple monster with complicated follow-up.' }),
  foe('FOE_ORCS', 'A Lot of Orcs', 10, 3, { type: 'ROLL_LOSE_GLORY' }, { specialRules: [{ type: 'BONUS_AGAINST_ORIGIN', originMechanicalSlot: 'DWARF_EQUIV', amount: 6 }], publicText: '+6 against Deepborn. Bad News: roll a die; on 1-2, lose that many Glory; otherwise lose as many Glory as the die shows.', flavorText: 'Nobody counted correctly, which is part of the problem.', enforcement: 'AUTO' }),
  foe('FOE_WANNABE_VAMPIRE', 'Wannabe Vampire', 12, 3, { type: 'LOSE_RENOWN', amount: 3, minimum: 1 }, { publicText: 'A Gravefriend may chase it away without gaining Glory, but draw its Loot. Bad News: lose 3 Glory.', flavorText: 'Very dramatic. Not quite certified.' }),
  foe('FOE_BIGFOOT', 'Hugefoot', 12, 3, { type: 'DISCARD_GEAR', target: 'EQUIPPED_GEAR', slot: 'HEAD', choice: 'PLAYER' }, { specialRules: [{ type: 'BONUS_AGAINST_ORIGIN', originMechanicalSlot: 'DWARF_EQUIV', amount: 3 }, { type: 'BONUS_AGAINST_ORIGIN', originMechanicalSlot: 'HALFLING_EQUIV', amount: 3 }], publicText: '+3 against Deepborn and Halfsteps. Bad News: lose equipped Head Gear.', flavorText: 'The foot arrives before the explanation.' }),
  foe('FOE_TONGUE_DEMON', 'Tongue Demon', 12, 3, { type: 'LOSE_RENOWN', amount: 2, minimum: 1 }, { specialRules: [{ type: 'BONUS_AGAINST_ROLE', roleMechanicalSlot: 'CLERIC_EQUIV', amount: 4 }], publicText: '+4 against Gravefriends. Bad News: lose 2 Glory; Brightkin lose 3 Glory.', flavorText: 'A mouth with career goals.', enforcement: 'AUTO' }),
  foe('FOE_STONED_GOLEM', 'Mossy Golem', 14, 4, { type: 'KNOCKOUT' }, { publicText: 'You may choose not to fight and walk past it. Halfsteps must fight. Bad News: Knockout.', flavorText: 'Patient enough to be mistaken for scenery.', enforcement: 'AUTO' }),
  foe('FOE_INSURANCE', 'Insurance Salesman', 14, 4, { type: 'DISCARD_GEAR_VALUE_OR_ALL', value: 1000 }, { publicText: 'Fight him only with your Gear bonuses, not Glory. Bad News: lose 1000 Junk worth of Gear, or all you have.', flavorText: 'Coverage begins after the screaming stops.', enforcement: 'AUTO' }),
  foe('FOE_HORROR', 'Unspeakable Hallway Horror', 14, 4, { type: 'KNOCKOUT' }, { specialRules: [{ type: 'BONUS_AGAINST_ROLE', roleMechanicalSlot: 'WARRIOR_EQUIV', amount: 4 }], publicText: '+4 against Bruisers. Bad News: Knockout unless you are a Hexhand and discard that Calling.', flavorText: 'It has too many adjectives and most of them are teeth.', enforcement: 'AUTO' }),
  foe('FOE_HIPPOGRIFF', 'Hippogriff', 16, 4, { type: 'KNOCKOUT' }, { renownReward: 2, willNotPursue: [{ type: 'RENOWN_BELOW', value: 4 }], publicText: 'Will not pursue anyone below 4 Glory. Defeat it to gain 2 Glory and 4 Loot. Bad News: Knockout.', flavorText: 'Majestic from a distance. Administrative up close.' }),
  foe('FOE_KING_TUT', 'Restless King', 16, 4, { type: 'DISCARD_HAND_AND_GEAR' }, { renownReward: 2, tags: ['RESTLESS'], willNotPursue: [{ type: 'RENOWN_BELOW', value: 4 }], publicText: 'Restless. Will not pursue anyone below 4 Glory. Higher-Glory players lose 2 Glory even if they escape. Bad News: lose all Gear and hand cards.', flavorText: 'The crown is real. The patience is not.', enforcement: 'AUTO' }),
  foe('FOE_WIGHT_BROTHERS', 'Restless Brothers', 16, 4, { type: 'LOSE_RENOWN', amount: 99, minimum: 1 }, { renownReward: 2, tags: ['RESTLESS'], willNotPursue: [{ type: 'RENOWN_BELOW', value: 4 }], publicText: 'Restless. Will not pursue anyone below 4 Glory. Higher-Glory players lose 2 Glory even if they escape. Bad News: reduced to Glory 1.', flavorText: 'Family business. Terrible hours.' }),
  foe('FOE_BULLROG', 'Bullrog', 18, 5, { type: 'KNOCKOUT' }, { renownReward: 2, willNotPursue: [{ type: 'RENOWN_BELOW', value: 5 }], publicText: 'Will not pursue anyone below 5 Glory. Defeat it to gain 2 Glory and 5 Loot. Bad News: Knockout.', flavorText: 'It is mostly fire and poor hallway planning.' }),
  foe('FOE_SQUIDZILLA', 'Squidzilla', 18, 4, { type: 'KNOCKOUT' }, { renownReward: 2, specialRules: [{ type: 'BONUS_AGAINST_ORIGIN', originMechanicalSlot: 'ELF_EQUIV', amount: 4 }], willNotPursue: [{ type: 'RENOWN_BELOW', value: 5 }], publicText: '+4 against Brightkin. Will not pursue anyone below 5 Glory except Brightkin. Bad News: Knockout.', flavorText: 'Slimy, dramatic, and weirdly selective.', enforcement: 'AUTO' }),
  foe('FOE_PLUTONIUM_DRAGON', 'Glowing Dragon', 20, 5, { type: 'KNOCKOUT' }, { renownReward: 2, willNotPursue: [{ type: 'RENOWN_BELOW', value: 6 }], publicText: 'Will not pursue anyone below 6 Glory. Defeat it to gain 2 Glory and 5 Loot. Bad News: Knockout.', flavorText: 'The treasure glows too, which seems relevant.' }),
  // Door combat-removal/replacement/specials moved into Chamber deck for source parity
  special('SPECIAL_OUT_TO_LUNCH', 'Lunch Break', 'Use during combat. All Foes leave. The fighter draws 2 Loot. No Glory.', 'The monster is on break. Please respect the union.', { type: 'OUT_TO_LUNCH' }, { deck: 'CHAMBER', timing: ['DURING_COMBAT'], enforcement: 'AUTO' }),
  special('SPECIAL_ILLUSION', 'Illusion Swap', 'Use during combat. Replace the current Foe with a Foe from your hand.', 'The old problem left. The new problem signed in.', { type: 'ILLUSION_SWAP' }, { deck: 'CHAMBER', timing: ['DURING_COMBAT'], enforcement: 'GUIDED' }),
  special('SPECIAL_DIVINE_INTERVENTION', 'Divine Scheduling Conflict', 'Play immediately when drawn or at any time from hand. All Gravefriends gain 1 Glory; this can win the game.', 'The ceiling opened and had opinions.', { type: 'DIVINE_INTERVENTION' }, { deck: 'CHAMBER', timing: ['ANY_TIME'], enforcement: 'AUTO' })

];

const lootCards = [
  // Persistent Gear / Items
  gear('GEAR_HELM_COURAGE', 'Bucket Helm', '+1 combat bonus. Head Gear.', 'Originally a bucket. Promoted during an emergency.', { slot: 'HEAD', combatBonus: 1, junkValue: 200, copies: 1 }),
  gear('GEAR_BADASS_BANDANA', 'Bravery Bandana', '+3 combat bonus. Head Gear. Usable only if you have no Kin.', 'A serious cloth for unserious confidence.', { slot: 'HEAD', combatBonus: 3, junkValue: 400, requiresNoKin: true }),
  gear('GEAR_POINTY_HAT', 'Pointy Thinking Hat', '+3 combat bonus. Head Gear. Usable only by Hexhands.', 'The point helps ideas leave faster, which is not always ideal.', { slot: 'HEAD', combatBonus: 3, junkValue: 400, usableByCallings: ['CALLING_HEXHAND'] }),
  gear('GEAR_HORNY_HELMET', 'Horned Panic Helm', '+1 combat bonus, or +3 if you are Brightkin. Head Gear.', 'Elegant, dramatic, and best used in rooms with wide doorways.', { slot: 'HEAD', combatBonus: 1, junkValue: 600, conditionalBonuses: [{ ifOrigin: 'KIN_BRIGHTKIN', combatBonus: 2 }] }),
  gear('GEAR_LEATHER_ARMOR', 'Questionable Armor', '+1 combat bonus. Body Gear.', 'Inspected, approved, and then quietly avoided by the inspector.', { slot: 'BODY', combatBonus: 1, junkValue: 200 }),
  gear('GEAR_SLIMY_ARMOR', 'Slimy Armor', '+1 combat bonus. Body Gear.', 'Hard to grab, easy to regret.', { slot: 'BODY', combatBonus: 1, junkValue: 200 }),
  gear('GEAR_FLAMING_ARMOR', 'Flaming Armor', '+2 combat bonus. Body Gear.', 'Keeps enemies back and conversations short.', { slot: 'BODY', combatBonus: 2, junkValue: 400 }),
  gear('GEAR_SHORT_WIDE_ARMOR', 'Short Wide Armor', '+3 combat bonus. Body Gear. Usable only by Deepborn.', 'Tailored for compact confidence.', { slot: 'BODY', combatBonus: 3, junkValue: 400, usableByOrigins: ['KIN_DEEPBORN'] }),
  gear('GEAR_MITHRIL_ARMOR', 'Mirrorbright Armor', '+3 combat bonus. Body Gear. Heavy. Not usable by Hexhands.', 'So polished that enemies can see the exact moment they reconsider.', { slot: 'BODY', combatBonus: 3, junkValue: 600, isHeavy: true, notUsableByCallings: ['CALLING_HEXHAND'] }),
  gear('GEAR_SANDALS_PROTECTION', 'Sandals of Protection', 'Foot Gear. Hexes drawn when opening a Chamber do not affect you, but Hexes played by other players still do.', 'They know which floorboards are legally cursed.', { slot: 'FEET', combatBonus: 0, junkValue: 700, enforcement: 'AUTO' }),
  gear('GEAR_BOOTS_FAST', 'Boots of Leaving', '+2 to Flee. Foot Gear.', 'They know the way out and would love to discuss it.', { slot: 'FEET', escapeBonus: 2, junkValue: 400 }),
  gear('GEAR_BOOTS_KICKING', 'Boots of Bad Decisions', '+2 combat bonus. Foot Gear.', 'Comfortable, durable, and rarely pointed in the correct direction.', { slot: 'FEET', combatBonus: 2, junkValue: 400 }),
  gear('GEAR_SNEAKY_SWORD', 'Sneaky Little Sword', '+2 combat bonus. Uses 1 Hand.', 'Small enough to misplace. Sharp enough to become everyone’s business.', { slot: 'HAND', handsUsed: 1, combatBonus: 2, junkValue: 400 }),
  gear('GEAR_BROAD_SWORD', 'Broad Sword', '+3 combat bonus. Uses 1 Hand.', 'A classic shape with a lot of opinions.', { slot: 'HAND', handsUsed: 1, combatBonus: 3, junkValue: 400 }),
  gear('GEAR_RAT_STICK', 'Rat on a Stick', '+1 combat bonus. Uses 1 Hand. You may discard it for automatic escape from Foes of strength 8 or lower.', 'Better than nothing, in the way stairs are better than falling.', { slot: 'HAND', handsUsed: 1, combatBonus: 1, junkValue: 0, enforcement: 'AUTO' }),
  gear('GEAR_TUBA_CHARM', 'Tuba of Charm', '+3 to Flee. Uses 1 Hand. Heavy. If you escape, gain one hidden Loot on the way out.', 'Loud enough to count as a plan.', { slot: 'HAND', handsUsed: 1, escapeBonus: 3, junkValue: 300, isHeavy: true, enforcement: 'AUTO' }),
  gear('GEAR_STAFF_NAPALM', 'Boomstick Wand', '+5 combat bonus. Uses 1 Hand. Usable only by Hexhands.', 'For spells that prefer making an entrance.', { slot: 'HAND', handsUsed: 1, combatBonus: 5, junkValue: 800, usableByCallings: ['CALLING_HEXHAND'] }),
  gear('GEAR_BOW_RIBBONS', 'Bow With Too Many Ribbons', '+4 combat bonus. Uses 2 Hands. Usable only by Brightkin.', 'Decorative until it is not.', { slot: 'HAND', handsUsed: 2, combatBonus: 4, junkValue: 800, usableByOrigins: ['KIN_BRIGHTKIN'] }),
  gear('GEAR_ELEVEN_FOOT_POLE', 'Bigger Pointy Stick', '+1 combat bonus. Uses 2 Hands.', 'For when the first pointy stick made some good arguments.', { slot: 'HAND', handsUsed: 2, combatBonus: 1, junkValue: 200 }),
  gear('GEAR_CHAINSAW', 'Saw of Dramatic Outcomes', '+3 combat bonus. Uses 2 Hands. Heavy.', 'Excellent at cutting through red tape, provided the red tape has a health bar.', { slot: 'HAND', handsUsed: 2, combatBonus: 3, junkValue: 600, isHeavy: true }),
  gear('GEAR_BUCKLER', 'Buckler of Swashing', '+2 combat bonus. Uses 1 Hand.', 'Looks defensive. Behaves theatrical.', { slot: 'HAND', handsUsed: 1, combatBonus: 2, junkValue: 400 }),
  gear('GEAR_SINGING_SWORD', 'Singing and Dancing Sword', '+2 combat bonus. Uses 1 Hand. Not usable by Cutpurses.', 'It knows choreography and no boundaries.', { slot: 'HAND', handsUsed: 1, combatBonus: 2, junkValue: 400, notUsableByCallings: ['CALLING_CUTPURSE'] }),
  gear('GEAR_CHEESE_GRATER', 'Cheese Grater of Peace', '+3 combat bonus. Uses 1 Hand. Usable only by Gravefriends.', 'Ceremonial, technically. Very persuasive, practically.', { slot: 'HAND', handsUsed: 1, combatBonus: 3, junkValue: 400, usableByCallings: ['CALLING_GRAVEFRIEND'] }),
  gear('GEAR_DAGGER_TREACHERY', 'Dagger of Treachery', '+3 combat bonus. Uses 1 Hand. Usable only by Cutpurses.', 'Small enough to hide. Petty enough to remember.', { slot: 'HAND', handsUsed: 1, combatBonus: 3, junkValue: 400, usableByCallings: ['CALLING_CUTPURSE'] }),
  gear('GEAR_RAPIER_UNFAIRNESS', 'Rapier of Unfairness', '+3 combat bonus. Uses 1 Hand. Usable only by Brightkin.', 'Elegant enough to make everyone suspicious.', { slot: 'HAND', handsUsed: 1, combatBonus: 3, junkValue: 600, usableByOrigins: ['KIN_BRIGHTKIN'] }),
  gear('GEAR_SWISS_ARMY_POLEARM', 'Overprepared Polearm', '+4 combat bonus. Uses 2 Hands. Heavy. Usable only if you have no Kin.', 'Keeps danger at a respectful distance.', { slot: 'HAND', handsUsed: 2, combatBonus: 4, junkValue: 600, isHeavy: true, requiresNoKin: true }),
  gear('GEAR_SHIELD_UBIQUITY', 'Shield of Ubiquity', '+4 combat bonus. Uses 1 Hand. Heavy. Usable only by Bruisers.', 'Always in the way, which is sometimes the point.', { slot: 'HAND', handsUsed: 1, combatBonus: 4, junkValue: 600, isHeavy: true, usableByCallings: ['CALLING_BRUISER'] }),
  gear('GEAR_HAMMER_KNEECAP', 'Hammer of Kneecapping', '+4 combat bonus. Uses 1 Hand. Usable only by Deepborn.', 'Short handle. Long consequences.', { slot: 'HAND', handsUsed: 1, combatBonus: 4, junkValue: 600, usableByOrigins: ['KIN_DEEPBORN'] }),
  gear('GEAR_GENTLEMENS_CLUB', 'Gentleperson’s Club', '+3 combat bonus. Uses 1 Hand.', 'Polite name. Blunt application.', { slot: 'HAND', handsUsed: 1, combatBonus: 3, junkValue: 400 }),
  gear('GEAR_MACE_SHARPNESS', 'Mace of Sharpness', '+4 combat bonus. Uses 1 Hand. Usable only by Gravefriends.', 'Blessed by tradition. Applied with enthusiasm.', { slot: 'HAND', handsUsed: 1, combatBonus: 4, junkValue: 600, usableByCallings: ['CALLING_GRAVEFRIEND'] }),
  gear('GEAR_HUGE_ROCK', 'Huge Useless Rock', '+3 combat bonus. Uses 2 Hands. Heavy. No Junk Value.', 'Too important to leave behind, for reasons no one has successfully explained.', { slot: 'HAND', handsUsed: 2, combatBonus: 3, junkValue: 0, isHeavy: true }),
  gear('GEAR_STEPLADDER', 'Stepladder', '+3 combat bonus. Heavy. Usable only by Halfsteps.', 'A bold answer to a vertical problem.', { slot: 'NO_SLOT', combatBonus: 3, junkValue: 400, isHeavy: true, usableByOrigins: ['KIN_HALFSTEP'] }),
  gear('GEAR_SPIKY_KNEES', 'Spiky Knees', '+1 combat bonus. No slot.', 'A time-honored negotiation stance.', { slot: 'NO_SLOT', combatBonus: 1, junkValue: 200 }),
  gear('GEAR_PANTYHOSE', 'Potion-Belt of Giant Strength', '+3 combat bonus. No slot. Not usable by Bruisers.', 'Stretchy, supportive, and hard to explain.', { slot: 'NO_SLOT', combatBonus: 3, junkValue: 600, notUsableByCallings: ['CALLING_BRUISER'] }),
  gear('GEAR_KNEEPADS', 'Knees of Persuasion', 'Players with higher Glory cannot refuse your Backup request or ask for a reward. You cannot win with compelled Backup.', 'Not begging. Vertical diplomacy.', { slot: 'NO_SLOT', junkValue: 600, enforcement: 'AUTO' }),
  gear('GEAR_TITLE', 'Fancy Title', '+3 combat bonus. No slot.', 'The title is ceremonial. The confidence is real.', { slot: 'NO_SLOT', combatBonus: 3, junkValue: 0 }),
  gear('GEAR_HIRELING', 'Little Helper', '+1 combat bonus. May carry and use one extra Gear for you. You may discard Little Helper while Fleeing to escape automatically. If Little Helper leaves play, its carried Gear goes with it.', 'Helpful, punctual, and not interested in discussing its past.', { slot: 'NO_SLOT', combatBonus: 1, extraHands: 1, junkValue: 0, enforcement: 'AUTO' }),


  gear('GEAR_BOOTS_GENERIC', 'Scuffed Boots', '+1 combat bonus. Foot Gear.', 'Reliable, muddy, and somehow always near the door.', { slot: 'FEET', combatBonus: 1, junkValue: 200 }),
  special('SPECIAL_SPARE_GLORY_A', 'Small Heroic Errand', 'Gain 1 Glory. Cannot give the final winning Glory.', 'A tiny achievement, properly notarized.', { type: 'GAIN_RENOWN', amount: 1, canWin: false }, { timing: ['ANY_TIME'] }),
  special('SPECIAL_SPARE_GLORY_B', 'Very Official Compliment', 'Gain 1 Glory. Cannot give the final winning Glory.', 'Everyone agreed it counted, eventually.', { type: 'GAIN_RENOWN', amount: 1, canWin: false }, { timing: ['ANY_TIME'] }),

  // One-shots / combat tricks
  trick('TRICK_NASTY_DRINK', 'Nasty Sports Drink', 'Use during any combat. +2 to either side. One-use.', 'It tastes like victory if victory was refrigerated badly.', { type: 'MODIFY_COMBAT_TOTAL', side: 'PLAYER', amount: 2 }, { junkValue: 200, enforcement: 'AUTO' }),
  trick('TRICK_FLAMING_POISON', 'Flaming Poison Potion', 'Use during any combat. +3 to either side. One-use.', 'A little bottle of absolutely not.', { type: 'MODIFY_COMBAT_TOTAL', side: 'PLAYER', amount: 3 }, { junkValue: 100, enforcement: 'AUTO' }),
  trick('TRICK_FREEZING_EXPLOSIVE', 'Freezing Explosive Potion', 'Use during any combat. +3 to either side. One-use.', 'It freezes first, explodes second, and explains never.', { type: 'MODIFY_COMBAT_TOTAL', side: 'PLAYER', amount: 3 }, { junkValue: 100, enforcement: 'AUTO' }),
  trick('TRICK_MAGIC_MISSILE_A', 'Magic Missile', 'Use during any combat. +5 to either side. One-use.', 'Nobody knows what it does until someone confidently points it at a problem.', { type: 'MODIFY_COMBAT_TOTAL', side: 'PLAYER', amount: 5 }, { junkValue: 300, enforcement: 'AUTO' }),
  trick('TRICK_PRETTY_BALLOONS', 'Pretty Balloons', 'Use during any combat. +5 to either side. One-use.', 'A colorful distraction with surprisingly firm opinions.', { type: 'MODIFY_COMBAT_TOTAL', side: 'PLAYER', amount: 5 }, { junkValue: 0, enforcement: 'AUTO' }),
  trick('TRICK_HALITOSIS', 'Potion of Halitosis', 'Use during any combat. +2 to either side, or instantly defeats the Hovering Nose. One-use.', 'A tactical cloud with social consequences.', { type: 'MODIFY_COMBAT_TOTAL', side: 'PLAYER', amount: 2 }, { junkValue: 100, enforcement: 'AUTO' }),
  trick('TRICK_SLEEP_POTION', 'Sleep Potion', 'Use during any combat. +2 to either side. One-use.', 'A bedtime story in liquid form.', { type: 'MODIFY_COMBAT_TOTAL', side: 'PLAYER', amount: 2 }, { junkValue: 100, enforcement: 'AUTO' }),
  trick('TRICK_ACID_POTION', 'Fizzing Acid Potion', 'Use during any combat. +5 to either side. One-use.', 'Not all treasure is glamorous. Some of it hisses.', { type: 'MODIFY_COMBAT_TOTAL', side: 'PLAYER', amount: 5 }, { junkValue: 200, enforcement: 'AUTO' }),
  trick('TRICK_YUPPIE_WATER', 'Fancy Sparkling Water', 'Use during combat. Usable only by and to help Brightkin. +2 to each Brightkin in the battle.', 'Bubbly, expensive, and somehow tactical.', { type: 'YUPPIE_WATER' }, { junkValue: 100, enforcement: 'AUTO' }),
  trick('TRICK_COTION_PONFUSION', 'Potion of Confusion', 'Use during any combat. +3 to either side. One-use.', 'Everyone agrees something happened. Accounts differ on whether it helped.', { type: 'MODIFY_COMBAT_TOTAL', side: 'PLAYER', amount: 3 }, { junkValue: 100, enforcement: 'AUTO' }),
  trick('TRICK_DOPPELGANGER', 'Doppelgoblin', 'Use during your combat if you have no helper. Add your current combat strength again to the player side.', 'Finally, someone who understands the plan and is also the problem.', { type: 'DOPPELGANGER' }, { junkValue: 300, enforcement: 'AUTO' }),
  trick('TRICK_INVISIBILITY', 'Invisibility Potion', 'Use after your Flee roll fails. You automatically escape. One-use.', 'For when the bravest thing to be is unavailable.', { type: 'AUTO_ESCAPE' }, { timing: ['AFTER_FAILED_ESCAPE'], junkValue: 200 }),
  trick('TRICK_FLASK_GLUE', 'Flask of Glue', 'Use after someone successfully Flees. That player must reroll that Flee attempt.', 'A small administrative pause in someone else’s exit.', { type: 'FORCE_REROLL_FLEE' }, { timing: ['AFTER_ESCAPE_ROLL'], junkValue: 100, enforcement: 'AUTO' }),
  trick('TRICK_INSTANT_WALL', 'Instant Wall', 'Play before a Flee roll. The current runner automatically escapes this Foe.', 'A door would have been polite. This is faster.', { type: 'AUTO_ESCAPE' }, { timing: ['BEFORE_ESCAPE_ROLL'], junkValue: 300, enforcement: 'AUTO' }),

  // Special treasures / rule-breakers / Go Up a Glory
  special('SPECIAL_GO_UP_GENERAL', 'Potion of General Studliness', 'Play at any time. Gain 1 Glory. Cannot give the final winning Glory.', 'Not heroic exactly, but everyone did look.', { type: 'GAIN_RENOWN', amount: 1, canWin: false }, { timing: ['ANY_TIME'], copies: 1 }),
  special('SPECIAL_KILL_HIRELING', 'Dismiss the Helper', 'Choose a player with Little Helper. Discard that Little Helper and gain 1 Glory. Any Gear carried by that Helper is discarded too.', 'A personnel decision with dramatic timing.', { type: 'KILL_HIRELING_GAIN_GLORY' }, { timing: ['ANY_TIME'], target: 'ANY_PLAYER', enforcement: 'GUIDED' }),
  special('SPECIAL_INVOKE_RULES', 'Invoke Obscure Rules', 'Gain 1 Glory. Cannot give the final winning Glory.', 'A small legal door in a large illegal wall.', { type: 'GAIN_RENOWN', amount: 1, canWin: false }, { timing: ['ANY_TIME'] }),
  special('SPECIAL_MUTILATE_BODIES', 'Check the Pockets', 'Play after any combat. Gain 1 Glory.', 'Archaeology, if the artifact is still warm.', { type: 'GAIN_RENOWN', amount: 1, canWin: false }, { timing: ['ANY_TIME'], enforcement: 'AUTO' }),
  special('SPECIAL_BOIL_ANTHILL', 'Boil an Anthill', 'Gain 1 Glory. Cannot give the final winning Glory.', 'The less said about the method, the better.', { type: 'GAIN_RENOWN', amount: 1, canWin: false }, { timing: ['ANY_TIME'] }),
  special('SPECIAL_BRIBE_GM', 'Bribe the Dungeon', 'Gain 1 Glory. Cannot give the final winning Glory.', 'The dungeon denies all allegations and accepts snacks.', { type: 'GAIN_RENOWN', amount: 1, canWin: false }, { timing: ['ANY_TIME'] }),
  special('SPECIAL_WHINE_GM', 'Complain to the Walls', 'Use only if you are tied for or have the highest Glory. Gain 1 Glory.', 'The walls are listening, unfortunately.', { type: 'GAIN_IF_HIGHEST_OR_TIED', amount: 1 }, { timing: ['ANY_TIME'], enforcement: 'AUTO' }),
  special('SPECIAL_GOLD_1000', '1000 Junk Voucher', 'Gain 1 Glory by cashing this in, unless it would be the final winning Glory.', 'Not money, but money’s weird cousin.', { type: 'GAIN_RENOWN', amount: 1, canWin: false }, { timing: ['OWN_TURN_OUTSIDE_COMBAT'] }),
  special('SPECIAL_ADDITION_ERROR', 'Convenient Addition Error', 'Gain 1 Glory. Cannot give the final winning Glory.', 'Everyone remembers the math differently.', { type: 'GAIN_RENOWN', amount: 1, canWin: false }, { timing: ['ANY_TIME'] }),
  special('SPECIAL_LOADED_DIE', 'Loaded Die', 'Play after you roll a die. Choose the die result instead.', 'A tiny cube with very flexible ethics.', { type: 'SET_DIE_ROLL' }, { timing: ['REACTION_TO_DIE_ROLL'], junkValue: 300, enforcement: 'GUIDED' }),
  special('SPECIAL_WISHING_RING_A', 'Wish Ring', 'Cancel the last revealed or played Hex affecting you, if one is pending. Otherwise keep it as a reaction card.', 'The wish is small, legal, and very smug.', { type: 'CANCEL_ACTIVE_HEX' }, { timing: ['REACTION_TO_HEX','ANY_TIME'], junkValue: 500, enforcement: 'AUTO', copies: 2 }),
  special('SPECIAL_MAGIC_LAMP', 'Magic Lamp', 'Play during combat or Flee. One Foe vanishes. You gain no Glory, but take that Foe’s Loot.', 'The genie prefers clear requests and low expectations.', { type: 'REMOVE_FOE_LOOT_ONLY' }, { timing: ['DURING_COMBAT', 'BEFORE_ESCAPE_ROLL'], junkValue: 500, enforcement: 'AUTO' }),
  special('SPECIAL_POLYMORPH', 'Polymorph Potion', 'Use during combat. One Foe flies away, leaving its Loot. No Glory.', 'A monster became a scheduling issue with wings.', { type: 'REMOVE_FOE_LOOT_ONLY' }, { timing: ['DURING_COMBAT'], junkValue: 1300, enforcement: 'AUTO' }),
  special('SPECIAL_TRANSFERRAL', 'Transfer Potion', 'Use during combat. Choose another player; they become the fighter for this combat.', 'A brave decision made for someone else.', { type: 'TRANSFER_COMBAT' }, { timing: ['DURING_COMBAT'], target: 'OTHER_PLAYER', junkValue: 300, enforcement: 'GUIDED' }),
  special('SPECIAL_WAND_DOWSING', 'Wand of Dowsing', 'Choose any card from either discard pile and put it into your hand.', 'Everything is lost until someone labels the box.', { type: 'WAND_DOWSING' }, { timing: ['OWN_TURN_OUTSIDE_COMBAT'], junkValue: 1100, enforcement: 'GUIDED' }),
  special('SPECIAL_HOARD', 'Hoard!', 'Draw 3 Loot immediately.', 'The dungeon restocked while you were making poor choices.', { type: 'DRAW_LOOT', count: 3 }, { timing: ['ANY_TIME'] }),
  special('SPECIAL_FRIENDSHIP', 'Friendship Potion', 'Use during combat. Discard all Foes. No Glory or Loot; the fighter draws one hidden Chamber card.', 'A peaceful solution that still feels suspicious.', { type: 'FRIENDSHIP_END' }, { timing: ['DURING_COMBAT'], junkValue: 200, enforcement: 'AUTO' }),
  special('SPECIAL_STEAL_LEVEL', 'Steal a Glory', 'Choose another player. They lose 1 Glory, to a minimum of 1, and you gain 1 Glory. This cannot give you the final winning Glory.', 'A ladder made of someone else’s applause.', { type: 'TRANSFER_RENOWN', amount: 1, minimum: 1, canWin: false }, { timing: ['ANY_TIME'], target: 'OTHER_PLAYER', enforcement: 'AUTO' })
];

module.exports = { chamberCards, lootCards };
